language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO="django==1.6"
  - DJANGO="django==1.5"
  - DJANGO="django==1.4"

install:
  - pip install $DJANGO

script:
  - python runtests.py

matrix:
  exclude:
  - python: "3.2"
    env: DJANGO="django==1.4"
  - python: "3.3"
    env: DJANGO="django==1.4"

branches:
  only:
    - master