language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO="django==1.6.2"
  - DJANGO="django==1.5.5"
  - DJANGO="django==1.4.10"

install:
  - pip install $DJANGO

script:
  - python runtests.py

matrix:
  exclude:
  - python: "3.2"
    env: DJANGO=1.4.2
  - python: "3.3"
    env: DJANGO=1.4.2

branches:
  only:
    - master