sudo: false
language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5


install:
    - pip install Django${DJANGO_VERSION}

env:
  matrix:
    - DJANGO_VERSION=">=1.6,<1.7"
    - DJANGO_VERSION=">=1.7,<1.8"
    - DJANGO_VERSION=">=1.8,<1.9"
    - DJANGO_VERSION=">=1.9,<1.10"

matrix:
  exclude:
    - python: 3.5
      env: DJANGO_VERSION=">=1.6,<1.7"
    - python: 3.5
      env: DJANGO_VERSION=">=1.7,<1.8"
    - python: 3.3
      env: DJANGO_VERSION=">=1.9,<1.10"
    - python: 3.2
      env: DJANGO_VERSION=">=1.9,<1.10"

branches:
  only:
    - master

script:
  - python runtests.py
