sudo: false
language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

install:
    - pip install Django${DJANGO_VERSION}
    - pip install codecov

env:
  matrix:
    - DJANGO_VERSION=">=1.8,<1.9"
    - DJANGO_VERSION=">=1.9,<1.10"
    - DJANGO_VERSION=">=1.10,<1.11"
    - DJANGO_VERSION=">=1.11,<2.0.0"

matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=">=1.9,<1.10"
    - python: 3.3
      env: DJANGO_VERSION=">=1.10,<1.11"
    - python: 3.3
      env: DJANGO_VERSION=">=1.11,<2.0.0"
    - python: 3.4
      env: DJANGO_VERSION=">=1.11,<2.0.0"

branches:
  only:
    - master

script:
  - coverage run --omit='setup.py' --source='.' runtests.py

after_success:
  - codecov
